export const EVENT_KINDS = ["swap", "bridge"] as const;
export const EVENT_ROLES = ["swap", "bridge_deposit", "bridge_fill_expected", "bridge_fill_observed", "bridge_refund"] as const;
export const EVENT_STATUSES = ["pending", "confirmed", "definitively_failed"] as const;
export const CHAIN_FAMILIES = ["eip155", "solana"] as const;
export const FAILURE_CODES = ["route_not_found", "slippage", "deadline_expired", "insufficient_liquidity", "allowance_or_balance", "chain_unsupported", "simulation_reverted", "mined_revert", "broadcast_error", "confirmation_timeout", "unknown", "bridge_failed", "bridge_refunded"] as const;
export const BANNED_INGEST_FIELDS = ["wallet_address", "from_address", "session_id", "nonce", "failure_reason", "route_provenance"] as const;
export type EventStatus = (typeof EVENT_STATUSES)[number];
export type EventRole = (typeof EVENT_ROLES)[number];
export type FailureCode = (typeof FAILURE_CODES)[number];
